name: CI

on:
   pull_request:
   push:
      branches: [develop]
   workflow_dispatch:

permissions:
   contents: read

jobs:
   build-test:
      runs-on: ubuntu-latest
      timeout-minutes: 15

      defaults:
         run:
            working-directory: frontend # << seu app está na pasta frontend

      steps:
         - uses: actions/checkout@v4

         - name: Use Node 20
           uses: actions/setup-node@v4
           with:
              node-version: 20
              cache: npm
              cache-dependency-path: frontend/package-lock.json

         - name: Install deps (ci)
           run: npm ci --no-audit --no-fund

         - name: Test
           run: npm test -- --watch=false --browsers=ChromeHeadless

         - name: Build
           run: npm run build --if-present

         - name: Upload artifact (dist)
           if: ${{ success() }}
           uses: actions/upload-artifact@v4
           with:
              name: dist
              path: |
                 frontend/dist/**
                 frontend/build/**
              if-no-files-found: ignore
