name: CI

on:
   push:
      branches: [develop, feature/**]
   pull_request:
      branches: [develop, master]
   workflow_dispatch:

permissions:
   contents: read

jobs:
   build-test:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      strategy:
         fail-fast: false
         matrix:
            node-version: [18, 20]

      steps:
         - uses: actions/checkout@v4

         - name: Use Node ${{ matrix.node-version }}
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
              cache-dependency-path: frontend/package-lock.json

         - name: Install deps (ci)
           working-directory: frontend
           run: npm ci

         - name: Test
           working-directory: frontend
           run: npm test -- --watch=false --browsers=ChromeHeadless

         - name: Build
           working-directory: frontend
           run: npm run build --if-present

         - name: Upload artifact (dist)
           if: success()
           uses: actions/upload-artifact@v4
           with:
              name: dist
              path: |
                 frontend/dist/**
                 frontend/build/**
              if-no-files-found: ignore
